In [1]:
#matrix multiplication, including matrix-vector multiplication, can be performed using the matmul function in NumPy

In [2]:
import numpy as np

In [6]:
ket0 = np.array([[1], [0]])

In [7]:
ket1 = np.array([[0], [1]])

In [ ]:
M1 = np.array([[1,1],[0,0]])

In [8]:
M2 = np.array([[1,0], [0,1]])

In [9]:
M = M1/2 + M2/2

In [10]:
print(M)

[[1.  0.5]
 [0.  0.5]]


In [11]:
print(np.matmul(M1, ket1)) #multiplying matrix M1 to column vector ket1

[[1]
 [0]]


In [12]:
print(np.matmul(M1, M2)) #multiplying two matrices M1 and M2

[[1 1]
 [0 0]]


In [13]:
print(np.matmul(M, M)) #multiplying matrix M to itself

[[1.   0.75]
 [0.   0.25]]


In [14]:
#array_to_latex function from the qiskit_visualization module can help improve the formatting

In [17]:
from qiskit.visualization import array_to_latex

In [ ]:
display(array_to_latex(np.matmul(M